apiVersion: v1
kind: Service
metadata:
  name: demo
spec:
  type: NodePort
  selector:
    app: demo
  ports:
  - port: 29994
    targetPort: 29994

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: promote-demo
  labels:
    app: demo
spec:
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: demo
        image: $IMAGE
        imagePullPolicy: Always
        ports:
        - containerPort: 30001
